### ISSUE TITLE
110 Angular Snippets

### ISSUE THREAD

**Issue by BeastCode** [doggy8088/angular-extension-pack#1]
Hi, check out:

https://marketplace.visualstudio.com/items?itemName=Mikael.Angular-BeastCode

It has over 110 snippets for Angular  /Mike

**Comment by doggy8088** [comment]
@BeastCode Yes, this is a good extension and most of them are useful.  But I think some of the snippets are too explicit pre-defined which not fit some of my dev scenario.  For example, the `ng-for` will generate `let ${item} of ${item}s` which we are not often use that naming rules.  So that I choose johnpapa's snippet at this time.

**Comment by BeastCode** [comment]
Thanks for the feedback! You right, I will update that! Would love to hear any of your other suggestions. Are you twitter? / @mike_beastcode

**Comment by doggy8088** [comment]
@BeastCode Yup, here: https://twitter.com/Will_Huang

**Comment by BeastCode** [comment]
Fixed in v4.1.14

**Comment by doggy8088** [comment]
@BeastCode Here is a quick question.  Do you know how to disable built-in ng 1.x snippets in vscode?  When I press `ng-` all the snippets are ng 1.x snippets and your's snippets are at the bottom of the long list.

![image](https://cloud.githubusercontent.com/assets/88981/26027135/d6f71124-383a-11e7-8cda-7e36abeb83de.png)

**Comment by BeastCode** [comment]
There shouldn't be any built-in snippets in VSCode, I don't see these in my
editor. What does it say all the way to the right in the menu after ng-app?

These is also a setting to see snippets first:
  "editor.snippetSuggestions": "top"

**Comment by doggy8088** [comment]
@BeastCode The [new version](https://marketplace.visualstudio.com/items?itemName=doggy8088.angular-extension-pack) was just released.  Thanks for your contribution.  👍
