### ISSUE TITLE
Angular Component Extension is a good plugin

### ISSUE THREAD

**Issue by snoopy-rui** [doggy8088/angular-extension-pack#11]
you can go to definition from html template

**Comment by doggy8088** [comment]
@snoopy-rui This  is really an awesome extension.  Let me find some time to add to my extension pack!

Thanks for sharing! 👍

**Comment by doggy8088** [comment]
@snoopy-rui I don't use **inline template** at all.  So I may add this extension to the README but add to my extension pack.  Thanks for your suggestion. 👍

**Comment by doggy8088** [comment]
It's been added to the [v0.8.2](https://marketplace.visualstudio.com/items?itemName=doggy8088.angular-extension-pack).
