### ISSUE TITLE
Angular-io-Code useless

### ISSUE THREAD

**Issue by jimiatworking** [doggy8088/angular-extension-pack#13]
Hi, I'm seeing Angular-io-Code just have 1 star on Marketplace. Do you think it's usefully?

**Comment by doggy8088** [comment]
I agreed your comment.  It's better to decouple the theme and all other extensions.

I already [updated it](https://marketplace.visualstudio.com/items?itemName=doggy8088.angular-extension-pack) and the new version is `0.9.1`.
