### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by jorgeLoa** [doggy8088/angular-extension-pack#19]
Is good idea to add SCSS Formatter ans SCSS Intellisense

Anyway, your pack is the best!

**Comment by doggy8088** [comment]
To be specific, are you saying the [SCSS Formatter](https://marketplace.visualstudio.com/items?itemName=sibiraj-s.vscode-scss-formatter) and [SCSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss) extension?

**Comment by jorgeLoa** [comment]
Exactly,  SCSS Formatter and SCSS IntelliSense
