### ISSUE TITLE
Quokka.js

### ISSUE THREAD

**Issue by doggy8088** [doggy8088/angular-extension-pack#2]
-- | Description
----------- |-----------
Extension | [Quokka.js](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)
Description | The Live Scratchpad for JavaScript
Publisher | [Wallaby.js](https://marketplace.visualstudio.com/search?term=publisher%3A%22Wallaby.js%22&target=VSCode&category=All%20categories&sortBy=Relevance)
Website | https://quokkajs.com
Reason | It is a rapid prototyping playground in your editor, with access to your project's files, inline reporting, code coverage and rich output formatting.

**Comment by tonivj5** [comment]
This tool would be awesome!! :+1:
