### ISSUE TITLE
Productivity Extension: Angular File Changer

### ISSUE THREAD

**Issue by jtcrowson** [doggy8088/angular-extension-pack#22]
[Marketplace Link](https://marketplace.visualstudio.com/items?itemName=john-crowson.angular-file-changer)

Easy way to switch between angular component files using Touch Bar or keyboard.  Also works with NgRx.

**Comment by jtcrowson** [comment]
@doggy8088 is this extension pack still being maintained?

**Comment by doggy8088** [comment]
@jtcrowson Yes :)

**Comment by doggy8088** [comment]
I already have the [angular2-switcher](https://marketplace.visualstudio.com/items?itemName=infinity1207.angular2-switcher) extension.
