### ISSUE TITLE
Auto tag

### ISSUE THREAD

**Issue by HsuNick** [doggy8088/angular-extension-pack#8]
請問一下保哥，安裝完您的pack後，為什麼都沒有Auto Tag功能?

**Comment by doggy8088** [comment]
@boy28213 什麼叫做 **Auto Tag** 呢？

**Comment by HsuNick** [comment]
像這樣..

![](https://raw.githubusercontent.com/BeastCode/VSCode-Angular-TypeScript-Snippets/master/images/ngForSnippet.gif)

剛剛試過在新開一個專案下，他可以如上圖一樣出現功能，
但在自己的舊專案下卻無法出現這樣的功能。

![](http://i.imgur.com/U6BVlXC.png)

**Comment by doggy8088** [comment]
@boy28213 你好像應該要在 *.html 裡面，才能用 HTML 相關的 Snippets 喔

**Comment by doggy8088** [comment]
@boy28213 另外請你檢查一下你的 Visual Studio Code 是否有安裝【IntelliSense for CSS class names】這個擴充套件，如果有的話，建議先停用或移除。

[這個【IntelliSense for CSS class names】擴充套件，在更新到目前最新版 1.6.0 之後，所有在 Angular 元件 Template 的 Code Snippets 功能會全部壞掉！](https://www.facebook.com/groups/augularjs.tw/permalink/1636987382978292/)

**Comment by HsuNick** [comment]
@doggy8088 停用【IntelliSense for CSS class names】這個就好了，真的太謝謝will保哥。
